package com.model;

/**
 * TZhuanye generated by MyEclipse Persistence Tools
 */

public class TZhuanye implements java.io.Serializable
{

	private Integer id;
	private String mingcheng;
	private String del;
	
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	
	public String getDel()
	{
		return del;
	}
	public void setDel(String del)
	{
		this.del = del;
	}
	public String getMingcheng()
	{
		return mingcheng;
	}
	public void setMingcheng(String mingcheng)
	{
		this.mingcheng = mingcheng;
	}

}